// Seed data used by the Setup wizard (/setup) and the DataInit page (/init).
// Exported as a default object so the Setup page can dynamic-import it.

const projects = [
  {
    id: 'fintech-explainer',
    slug: 'fintech-explainer',
    title: 'FinTech Product Launch',
    category: 'Product',
    year: 2024,
    description: '2.3M views, 340% increase in sign-ups',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    videoUrl: '',
    tags: ['Product', 'Animation', 'B2B'],
    featured: true,
    orderIndex: 1,
    client: 'TechCorp Financial',
    goal: 'Launch a new digital banking product to millennials with a clear value proposition and a seamless onboarding flow explanation.',
    approach: 'Created a fast-paced, modern explainer combining bold typography, smooth transitions, and real UI demonstrations. Focus on trust-building and simplicity.',
    deliverables: ['90-second explainer video', 'Social media cutdowns (15s, 30s, 60s)', 'Animated UI components library', 'Brand motion guidelines'],
    outcome: '2.3M views in first month. 340% increase in sign-ups. Featured on Product Hunt.',
    screenshots: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80', 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&q=80'],
  },
  {
    id: 'saas-onboarding',
    slug: 'saas-onboarding',
    title: 'SaaS Onboarding Flow',
    category: 'Product',
    year: 2024,
    description: '40% faster user activation',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    videoUrl: '',
    tags: ['SaaS', 'UI/UX', 'Motion'],
    featured: false,
    orderIndex: 2,
    client: 'CloudSoft Inc',
    goal: 'Reduce user drop-off during onboarding and increase activation rates through clear visual guidance.',
    approach: 'Designed animated micro-interactions and step-by-step tutorials that guide users through the product setup process.',
    deliverables: ['Onboarding video series', 'Interactive UI animations', 'Tutorial overlays', 'Success state animations'],
    outcome: '40% faster user activation and 25% reduction in support tickets.',
    screenshots: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80'],
  },
  {
    id: 'brand-identity',
    slug: 'brand-identity',
    title: 'Tech Brand Identity',
    category: 'Brand',
    year: 2023,
    description: 'Complete visual system in 3 weeks',
    imageUrl: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80',
    videoUrl: '',
    tags: ['Branding', 'Identity', 'Tech'],
    featured: true,
    orderIndex: 3,
    client: 'InnovateTech',
    goal: 'Create a modern, cohesive brand identity that positions the company as an innovative tech leader.',
    approach: 'Developed a comprehensive visual system including logo, color palette, typography, and motion guidelines.',
    deliverables: ['Brand logo & variations', 'Color system & guidelines', 'Typography system', 'Motion design principles', 'Brand guideline document'],
    outcome: 'Complete visual system delivered in 3 weeks. Brand recognition increased by 200%.',
    screenshots: ['https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&q=80', 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&q=80'],
  },
  {
    id: 'crypto-rebrand',
    slug: 'crypto-rebrand',
    title: 'Crypto Platform Rebrand',
    category: 'Brand',
    year: 2024,
    description: 'Brand recognition up 200%',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
    videoUrl: '',
    tags: ['Branding', 'Crypto', 'Web3'],
    featured: false,
    orderIndex: 4,
    client: 'BlockVault',
    goal: 'Reposition a legacy crypto exchange as a premium, trustworthy platform for institutional investors.',
    approach: 'Stripped back to core values — security, clarity, speed. New visual language uses geometric motion and dark-mode-first design.',
    deliverables: ['Full brand identity system', 'Motion style guide', 'App icon animations', 'Marketing video (60s)', 'Social media templates'],
    outcome: 'Rebranding completed in 6 weeks. Platform signups up 200% in Q1 post-launch.',
    screenshots: ['https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=1200&q=80', 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80'],
  },
  {
    id: 'social-campaign',
    slug: 'social-campaign',
    title: 'Viral Social Campaign',
    category: 'Social',
    year: 2023,
    description: '5M impressions in 2 weeks',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
    videoUrl: '',
    tags: ['Social Media', 'Campaign', 'Viral'],
    featured: false,
    orderIndex: 5,
    client: 'FreshDrop Apparel',
    goal: 'Drive awareness of a limited-edition drop across TikTok and Instagram Reels.',
    approach: 'Produced 12 short-form videos (7–15 seconds each) optimised for native feel — no hard logos, just vibe-first storytelling.',
    deliverables: ['12 short-form videos', '30 static social graphics', 'Story templates (IG + TikTok)', 'Caption & hashtag strategy doc'],
    outcome: '5M impressions in 14 days. Drop sold out in 4 hours. 180K new followers gained.',
    screenshots: ['https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&q=80'],
  },
  {
    id: 'ecommerce-ads',
    slug: 'ecommerce-ads',
    title: 'E-commerce Ad Series',
    category: 'Campaign',
    year: 2023,
    description: 'ROAS 8.5x across Meta & TikTok',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
    videoUrl: '',
    tags: ['Performance', 'Ads', 'E-commerce'],
    featured: false,
    orderIndex: 6,
    client: 'NovaSkin',
    goal: 'Build a scalable creative library for Meta and TikTok ads for a DTC skincare brand.',
    approach: 'Developed a modular creative system — hero hooks, product demos, UGC-style cuts, and testimonial edits — allowing rapid A/B testing.',
    deliverables: ['40 video ads (various formats)', 'Creative brief templates', '15 static/carousel ads', 'Monthly performance audit'],
    outcome: 'Average ROAS of 8.5x over 6 months. CPA down 60% from agency baseline.',
    screenshots: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80'],
  },
];

const tools = [
  {
    id: 'ae-automation-toolkit',
    name: 'AE Automation Toolkit',
    slug: 'ae-automation-toolkit',
    description: 'Professional automation suite for After Effects. Save hours on repetitive tasks with intelligent batch processing, smart cleanup tools, and advanced export management.',
    category: 'Automation',
    tagline: 'Stop doing the same tasks over and over. Let the toolkit handle it.',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',
    demoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    featured: true,
    orderIndex: 1,
    systemRequirements: 'After Effects CC 2020 or later\nmacOS 10.14+ or Windows 10+\n8GB RAM minimum (16GB recommended)\n500MB free disk space',
    howItWorks: [
      { title: 'Install the Script', description: 'Download and place the script in your After Effects ScriptUI Panels folder. Restart AE.' },
      { title: 'Configure Your Settings', description: 'Set up your preferred render settings, cleanup rules, and export presets once.' },
      { title: 'Automate Everything', description: 'Run batch operations on multiple projects with one click. Save hours every week.' },
    ],
    faqs: [
      { question: 'Does this work with the latest version of After Effects?', answer: 'Yes! We test and update the toolkit with every new AE release. Free updates included.' },
      { question: 'Can I use this for client work?', answer: 'Absolutely. All our tools come with a commercial license included in the purchase.' },
    ],
    versions: [
      {
        id: 'ae-toolkit-free',
        versionType: 'Free',
        pricingModel: 'lifetime',
        lifetimePrice: 'Free',
        downloadUrl: 'https://example.com/download/ae-toolkit-free.zip',
        features: ['Basic batch rendering (up to 5 projects)', 'Simple project cleanup', 'Standard export presets', 'Community support'],
        whatsIncluded: ['Core automation script', 'Basic documentation', 'Community forum access', 'Monthly updates'],
      },
      {
        id: 'ae-toolkit-pro',
        versionType: 'Pro',
        pricingModel: 'lifetime',
        lifetimePrice: '$49',
        downloadUrl: 'https://example.com/download/ae-toolkit-pro.zip',
        features: ['Unlimited batch rendering', 'Advanced cleanup rules', 'Custom export presets', 'Layer management tools', 'Expression utilities', 'Email support'],
        whatsIncluded: ['Full automation suite', 'Custom preset builder', 'Advanced documentation', 'Priority email support', 'Lifetime updates', 'Commercial license'],
      },
      {
        id: 'ae-toolkit-studio',
        versionType: 'Studio',
        pricingModel: 'subscription',
        monthlyPrice: '$29',
        yearlyPrice: '$249',
        downloadUrl: 'https://example.com/download/ae-toolkit-studio.zip',
        features: ['Everything in Pro', 'Network rendering support', 'Team collaboration tools', 'API access for integration', 'Priority support (24h response)', 'Dedicated account manager'],
        whatsIncluded: ['Complete Studio suite', 'Network render manager', 'Team license (up to 10 users)', 'API access & documentation', 'White-glove onboarding', 'Enterprise commercial license'],
      },
    ],
  },
  {
    id: 'motion-presets-pro',
    name: 'Motion Presets Pro',
    slug: 'motion-presets-pro',
    description: 'The ultimate collection of professional animation presets. Over 200 hand-crafted animations for text, shapes, transitions, and effects.',
    category: 'Animation',
    tagline: 'Professional animations, zero effort. Just drag and drop.',
    imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&q=80',
    demoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    featured: true,
    orderIndex: 2,
    systemRequirements: 'After Effects CC 2019 or later\nmacOS 10.13+ or Windows 10+\n4GB RAM minimum\n2GB free disk space for all presets',
    howItWorks: [
      { title: 'Browse the Library', description: 'Access 200+ categorized presets through our custom AE panel. Preview each animation before applying.' },
      { title: 'Drag & Drop', description: 'Simply drag any preset onto your layer. All parameters are automatically configured.' },
      { title: 'Customize & Export', description: 'Tweak timing, colors, and effects to match your brand. Render and deliver professional results.' },
    ],
    faqs: [
      { question: 'Are these presets compatible with older AE versions?', answer: 'The presets work with After Effects CC 2019 and later.' },
      { question: 'Can I customize the presets?', answer: 'Yes! All presets are fully editable.' },
    ],
    versions: [
      {
        id: 'motion-presets-free',
        versionType: 'Free',
        pricingModel: 'lifetime',
        lifetimePrice: 'Free',
        downloadUrl: 'https://example.com/download/motion-presets-free.zip',
        features: ['25 basic animation presets', 'Text animations', 'Simple transitions', 'Community support'],
        whatsIncluded: ['25 starter presets', 'Installation guide', 'Basic tutorial video'],
      },
      {
        id: 'motion-presets-pro-v',
        versionType: 'Pro',
        pricingModel: 'lifetime',
        lifetimePrice: '$79',
        downloadUrl: 'https://example.com/download/motion-presets-pro.zip',
        features: ['200+ professional presets', 'Text, shape & transition animations', 'VFX and particle effects', 'Monthly new preset packs', 'Email support'],
        whatsIncluded: ['Complete 200+ preset library', 'Custom browser panel', 'Full video course (3 hours)', 'Lifetime updates', 'Commercial license'],
      },
      {
        id: 'motion-presets-studio',
        versionType: 'Studio',
        pricingModel: 'subscription',
        monthlyPrice: '$19',
        yearlyPrice: '$159',
        downloadUrl: 'https://example.com/download/motion-presets-studio.zip',
        features: ['Everything in Pro', '500+ premium presets', 'Weekly new releases', 'Team sharing & sync', 'Priority support'],
        whatsIncluded: ['Complete 500+ preset library', 'Team cloud library (up to 5 users)', 'Weekly video tutorials', 'Enterprise commercial license'],
      },
    ],
  },
  {
    id: 'ae-expression-library',
    name: 'AE Expression Library',
    slug: 'ae-expression-library',
    description: 'A curated library of 150+ production-ready After Effects expressions. Stop writing code from scratch and ship faster.',
    category: 'Workflow',
    tagline: 'Copy, paste, animate. No coding knowledge required.',
    imageUrl: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=600&q=80',
    demoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    featured: false,
    orderIndex: 3,
    systemRequirements: 'After Effects CC 2018 or later\nmacOS 10.12+ or Windows 10+\n4GB RAM minimum\n150MB free disk space',
    howItWorks: [
      { title: 'Open the Panel', description: 'Launch the Expression Library panel from Window > Extensions. Browse by category or search by keyword.' },
      { title: 'Preview & Copy', description: 'Click any expression to see a live preview. Copy it to clipboard with one click.' },
      { title: 'Paste & Customise', description: 'Paste directly into an AE expression field. Adjust the highlighted variables for your project.' },
    ],
    faqs: [
      { question: 'Do I need to know how to code?', answer: 'No. Every expression has clearly labelled variables you can tweak without understanding the underlying code.' },
      { question: 'Is there a refund policy?', answer: 'Yes — 14-day no-questions-asked refund on all one-time purchases.' },
    ],
    versions: [
      {
        id: 'expr-lib-free',
        versionType: 'Free',
        pricingModel: 'lifetime',
        lifetimePrice: 'Free',
        downloadUrl: 'https://example.com/download/ae-expression-library-free.zip',
        features: ['20 essential expressions', 'Text counter & timer', 'Basic loop expressions', 'Community forum access'],
        whatsIncluded: ['20 starter expressions', 'Cheat-sheet PDF', 'Community forum access'],
      },
      {
        id: 'expr-lib-pro',
        versionType: 'Pro',
        pricingModel: 'lifetime',
        lifetimePrice: '$39',
        downloadUrl: 'https://example.com/download/ae-expression-library-pro.zip',
        features: ['150+ production-ready expressions', 'Dynamic text & counters', 'Procedural animation rigs', 'Physics simulations', 'Email support', 'Lifetime updates'],
        whatsIncluded: ['Complete 150+ expression library', 'In-panel search & preview', 'Full documentation site', 'Lifetime updates', 'Commercial license'],
      },
      {
        id: 'expr-lib-studio',
        versionType: 'Studio',
        pricingModel: 'subscription',
        monthlyPrice: '$15',
        yearlyPrice: '$129',
        downloadUrl: 'https://example.com/download/ae-expression-library-studio.zip',
        features: ['Everything in Pro', '250+ expressions & growing', 'Team expression vault', 'Custom expression requests (1/month)', 'Priority Slack support'],
        whatsIncluded: ['Complete 250+ expression library', 'Shared team vault (up to 8 users)', 'Private Slack community', 'Enterprise commercial license'],
      },
    ],
  },
];

const team = [
  {
    id: 'team-1',
    name: 'Alex Rivera',
    role: 'Motion Design Director',
    bio: '15+ years in motion design for global brands. Former creative lead at top agencies. Obsessed with the intersection of storytelling and technology.',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    orderIndex: 1,
    socialLinks: { linkedin: 'https://linkedin.com/in/alexrivera', twitter: 'https://twitter.com/alexrivera' },
  },
  {
    id: 'team-2',
    name: 'Sam Chen',
    role: 'Lead Animator',
    bio: 'Award-winning animator specialised in character animation and visual effects. Previously at Pixar and Framestore.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    orderIndex: 2,
    socialLinks: { linkedin: 'https://linkedin.com/in/samchen', dribbble: 'https://dribbble.com/samchen' },
  },
  {
    id: 'team-3',
    name: 'Nadia Osei',
    role: 'Creative Strategist',
    bio: 'Bridges the gap between brand strategy and motion design. 10+ years helping DTC and B2B brands find their visual voice.',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    orderIndex: 3,
    socialLinks: { linkedin: 'https://linkedin.com/in/nadiaosei', instagram: 'https://instagram.com/nadiaosei' },
  },
];

export default { projects, tools, team };
