// Default home content structure (matches HomeTab.tsx)
export const DEFAULT_HOME_CONTENT = {
  heroLine1: 'Premium motion design',
  heroLine2: 'for ambitious teams',
  heroSubtitle: 'High-end custom work that drives results. Remote collaboration with studios worldwide.',
  heroCta1Text: 'Work with us',
  heroCta2Text: 'View projects',
  showreelUrl: '',
  testimonialQuote: 'Fastoosh delivered exceptional work in record time. Their attention to detail and understanding of our brand was remarkable.',
  testimonialAuthor: 'Sarah Chen',
  testimonialRole: 'Head of Marketing at TechCorp',
  featuredHeading: 'Featured work',
  featuredSubtitle: 'Selected projects for ambitious brands',
  capabilitiesHeading: 'Why work with us',
  capabilities: [
    { icon: 'sparkles', title: 'Premium Craft', description: 'Every frame matters. Pixel-perfect attention to detail that elevates your brand.' },
    { icon: 'zap', title: 'Fast Turnaround', description: 'Structured process. Clear milestones. On-time delivery without compromising quality.' },
    { icon: 'target', title: 'Business Impact', description: 'Motion design that drives results. Conversion-focused, data-informed creative.' },
  ],
  processHeading: 'Our process',
  processSubtitle: 'Clear, structured, and collaborative',
  processSteps: [
    { number: '01', title: 'Discovery', description: 'Deep dive into your goals, brand, and audience' },
    { number: '02', title: 'Concept', description: 'Creative direction, styleframes, and motion tests' },
    { number: '03', title: 'Production', description: 'Animation, sound design, and refinement' },
    { number: '04', title: 'Delivery', description: 'Final assets + source files + documentation' },
  ],
  turnaroundRows: [
    { label: 'Short-form video', time: '1-2 weeks' },
    { label: 'Product explainer', time: '2-3 weeks' },
    { label: 'Brand identity', time: '3-4 weeks' },
    { label: 'Full campaign', time: '4-6 weeks' },
  ],
  turnaroundNote: 'Rush options available',
  deliverablesTitle: 'What you get',
  deliverables: [
    'Final rendered videos (all formats)',
    'Editable source files',
    'Brand guidelines (if needed)',
    'Sound design & music',
    'Unlimited revisions in scope',
    'Post-delivery support (30 days)',
  ],
  ctaHeading: 'Ready to create something',
  ctaHeadingGradient: 'extraordinary?',
  ctaSubtitle: "Let's discuss your project. We typically reply within 24-48 hours.",
  ctaBadges: ['✓ Reply in 24-48h', '✓ NDA-friendly', '✓ Remote worldwide'],
};
