/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ksndambbafpzxquxsgdw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbmRhbWJiYWZwenhxdXhzZ2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NDYzNjMsImV4cCI6MjA4NzMyMjM2M30.bZ2m03ZHXN4eSNiBN1ygE-OU73md-RudERUhKzNEPgg"